Repository fortemp/Software-Engineering, pull requests merged in 2021-06, with the labels that each got.

#38 추가: 테스트 케이스 명세서 최종
  testCase.docx
Labels: 시험계획서

#39 변경:분석클래스모델링-김민규
  AnalysisClassModeling-MingyuKim.docx
Labels: 요구사항명세서

#40 변경: 분석클래스 모델링-김민규
  AnalysisClassModeling-MingyuKim.docx
Labels: 설계문서

#41 변경: 시퀀스 다이어그램 통합 완료
  AnalysisClassModeling-YunkiKim.docx
Labels: 설계문서
