Repository fortemp/Software-Engineering, pull requests merged in 2021-05, with the labels that each got.

#20 회의: 네번째 회의록
  meeting_log/소프트웨어 공학 20210427회의록.docx
Labels: 회의록

#22 회의: 다섯번째 회의록
  meeting_log/소프트웨어 공학 20210504회의록.docx
Labels: 회의록

#23 회의: 여섯번째 회의
  meeting_log/소프트웨어 공학 20210506회의록.docx
Labels: 회의록

#24 추가:유스케이스정의서최종 초기본 완료
  FinalRequirementAnalysis-YunkiKim.docx
Labels: 요구사항명세서

#27 회의: 여덟번째 회의록
  meeting_log/소프트웨어 공학 20210510회의록.docx
Labels: 회의록

#28 변경: 5.11일수업의 피드팩에 의거하여 수정 김윤기
  FinalRequirementAnalysis-YunkiKim.docx
Labels: 요구사항명세서

#29 회의:여덟번째 회의록-
  meeting_log/소프트웨어 공학 20210513회의록.docx
Labels: 회의록

#30 변경: 회의 내용에 의거하여 유스케이스번호 수정, 김윤기
  FinalRequirementAnalysis-YunkiKim.docx
Labels: 요구사항명세서

#31 회의:아홉번째 회의록
  FinalRequirementAnalysis-MingyuKim.docx
  meeting_log/소프트웨어 공학 20210517회의록.docx
Labels: 회의록

#32 변경: 최종요구사항분석서_최종 백기원
  FinalRequirementAnalysis-KiwonBack.docx
Labels: 요구사항명세서

#33 변경: 최종 요구사항분석서 김민규
  FinalRequirementAnalysis-MingyuKim.docx
Labels: 요구사항명세서

#34 회의: 열번째 회의록
  meeting_log/소프트웨어 공학 20210520회의록.docx
Labels: 회의록

#35 회의: 열한번째 회의록
  AnalysisClassModeling-MingyuKim.docx
  meeting_log/소프트웨어 공학 20210527 회의록.docx
Labels: 회의록

#36 변경: 분석클래스모델링 백기원
  AnalysisClassModeling-KiwonBack.docx
Labels: 설계문서

#37 추가: 분석클래스모델링-김윤기 초본완료
  AnalysisClassModeling-YunkiKim.docx
Labels: 설계문서
